#!/usr/bin/env python3
import argparse
import sys
import os
from subprocess import call

def createProblem(problemNum):
    name = "Euler" + problemNum
    code = "public class " + name + """ {
    public static void main(String[] args) {
        long start = System.currentTimeMillis();

        System.out.println("Program took " 
            + (System.currentTimeMillis() - start) + "ms");
    }
}"""
    os.makedirs(name)
    file = open(name + "/" + name+".java", "w+")
    file.write(code)


def movefiles():
    for file in os.listdir():
        if file[-5:] == ".java":
            name = file[:-5]
            os.makedirs(name)
            os.rename(file, name+"/"+file)

def runProblem(num):
    directory = "Euler"+num
    filename = "Euler"+num+".java"
    call(["javac", directory+os.sep+filename])
    call(["cd", directory])
    call(["java", "Euler"+num])

def main():
    parser = argparse.ArgumentParser(description="solution manageer")
    parser.add_argument("-c", "--create", help="create solution of num", type=str)
    parser.add_argument("-e", "--execute", help="excute solution of num", type=str)

    args = parser.parse_args()
    if(args.create):
        createProblem(args.create)
    elif(args.execute):
        runProblem(args.execute)

main()